<?php

return [
    'Agriculteur / Agricultrice',
    'Agent d\'entretien',
    'Agent de sécurité',
    'Architecte',
    'Artisan / Artisane',
    'Assistant / Assistante maternel(le)',
    'Assistant / Assistante social(e)',
    'Avocat / Avocate',
    'Banquier / Banquière',
    'Bijoutier / Bijoutière',
    'Boucher / Bouchère',
    'Boulanger / Boulangère',
    'Caisse',
    'Chargé / Chargée de clientèle',
    'Charpentier / Charpentière',
    'Chauffeur / Chauffeuse',
    'Chef comptable',
    'Chef d\'entreprise',
    'Chef de chantier',
    'Chef de cuisine',
    'Chef de projet',
    'Chimiste',
    'Chirurgien / Chirurgienne',
    'Coiffeur / Coiffeuse',
    'Commerçant / Commerçante',
    'Commercial / Commerciale',
    'Comptable',
    'Conducteur / Conductrice de travaux',
    'Conseiller / Conseillère',
    'Consultant / Consultante',
    'Cuisinier / Cuisinière',
    'Dentiste',
    'Designer / Designeuse',
    'Développeur / Développeuse',
    'Directeur / Directrice',
    'Documentaliste',
    'Economiste',
    'Educateur / Éducatrice',
    'Electricien / Electricienne',
    'Employé / Employée de bureau',
    'Employé / Employée de maison',
    'Enseignant / Enseignante',
    'Esthéticien / Esthéticienne',
    'Expert / Experte comptable',
    'Facteur / Factrice',
    'Fleuriste',
    'Garagiste',
    'Gardien / Gardienne',
    'Gendarme',
    'Géomètre',
    'Gestionnaire de paie',
    'Graphiste',
    'Grutier / Grutière',
    'Hôte / Hôtesse d\'accueil',
    'Hôtelier / Hôtelière',
    'Infirmier / Infirmière',
    'Informaticien / Informaticienne',
    'Ingénieur / Ingénieure',
    'Inspecteur / Inspectrice',
    'Installateur / Installatrice',
    'Journaliste',
    'Juge',
    'Juriste',
    'Kinésithérapeute',
    'libraire',
    'Livreur / Livreuse',
    'Magon / Magonne',
    'Manager',
    'Mannequin',
    'Maraîcher / Maraîchère',
    'Marchand / Marchande',
    'Mécanicien / Mécanicienne',
    'Médecin',
    'Menuisier / Menuisière',
    'Militaire',
    'Musicien / Musicienne',
    'Notaire',
    'Nutritionniste',
    'Opérateur / Opératrice',
    'Opticien / Opticienne',
    'Orthophoniste',
    'Ouvrier / Ouvrière',
    'Pâtissier / Pâtissière',
    'Peintre',
    'Pharmacien / Pharmacienne',
    'Plombier / Plombière',
    'Policier / Policière',
    'Pompier',
    'Psychologue',
    'Puériculteur / Puéricultrice',
    'Réceptionniste',
    'Responsable RH',
    'Restaurateur / Restauratrice',
    'Retraité(e)',
    'Sage-femme',
    'Secrétaire',
    'Soudeur / Soudeuse',
    'Tailleur / Tailleuse',
    'Technicien / Technicienne',
    'Téléconseiller / Téléconseillère',
    'Vendeur / Vendeuse',
    'Vétérinaire',
    'Autre',
];
